FROM nginx:1.28.2-alpine
RUN echo "https://dl-cdn.alpinelinux.org/alpine/v3.20/community" >> /etc/apk/repositories \
  && apk add --no-cache nginx-mod-http-brotli
COPY nginx.conf /etc/nginx/nginx.conf
RUN nginx -t
