user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
  access_log /var/log/nginx/access.log main;

  sendfile on;
  keepalive_timeout 65;
  
  server {
    listen 80;

    # Clickjacking protection: allow framing only from same origin and Visit Health domains
    add_header Content-Security-Policy "frame-ancestors 'self' https://tatvapractice.getvisitapp.net https://tatvapractice.getvisitapp.com https://kea.getvisitapp.com https://hospital-dashboard.getvisitapp.net" always;

    location /case_manager/pdf_casemanager_send.php {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, X-Requested-With';
      add_header 'Access-Control-Allow-Credentials' 'true';
      proxy_pass https://pm-uat-dhspl-2.tatvacare.in;
    }

    location / {
      root /usr/share/nginx/html;
      index index.html index.htm;
      try_files $uri $uri/ /index.html =404;
    }
  }
}